dist: xenial
language: node_js
node_js:
    - "lts/dubnium"
install:
    - npm install
    - cd blockchain && npm install
    - cd client && npm install
script:
    - npm run install
    - npm run coverage:ci
